alias b  := build_pdflatex
alias bi := build_interactive

build_dir := "./latex"
build_opt := "-pdf -interaction=nonstopmode"

build_pdflatex:
    latexmk \
    -outdir={{build_dir}} \
    {{build_opt}}
          
    mv -f {{build_dir}}/main.pdf main.pdf

build_interactive:
    latexmk \
    -outdir={{build_dir}} \
    -pdf

    mv -f {{build_dir}}/main.pdf main.pdf
